version: '3.8'
services:
  db:
    image: postgres:15
    container_name: nestjslearning_postgres_db
    ports:
      - '5433:5432' # <--- CHANGED: Host 5433 -> Container 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestjs_mastery
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
